apiVersion: networking.k8s.io/v1  
kind: Ingress
metadata:
annotations:
    meta.helm.sh/release-name: iobroker
    meta.helm.sh/release-namespace: iobroker
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
name: iobroker-ingress
namespace: iobroker
spec:
  rules:
    - host: linux-2.fritz.box
      http:
        paths:
          - backend:
              service:
                name: iobroker-ingress-svc
                port:
                  number: 8081
            path: /
            pathType: Prefix
                      - backend:
              service:
                name: iobroker-ingress-svc
                port:
                  number: 8082
            path: /iqontrol
            pathType: Prefix
  tls:
    - hosts:
        - linux-2.fritz.box
      secretName: iobroker-tls
