apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iobroker-ingress
  namespace: iobroker
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    meta.helm.sh/release-name: iobroker
    meta.helm.sh/release-namespace: iobroker
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16,10.0.0.0/8"
spec:
  ingressClassName: traefik
  rules:
    - host: linux-2.fritz.box
      http:
        paths:
          - backend:
              service:
                name: iobroker-ingress-svc
                port:
                  number: 8081
            path: /
            pathType: Prefix
          - backend:
              service:
                name: iobroker-ingress-svc
                port:
                  number: 8082
            path: /iqontrol
            pathType: Prefix
  tls:
    - hosts:
        - linux-2.fritz.box
      secretName: iobroker-tls
