apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iobroker
  namespace: iobroker
spec:
  serviceName: iobroker
  selector:
    matchLabels:
      app: iobroker
  replicas: 1
  template:
    metadata:
      name: iobroker
      labels:
        app.kubernetes.io/managed-by: Helm
        meta.helm.sh/release-name: iobroker
        meta.helm.sh/release-namespace: default
        app: iobroker
    spec:
      hostname: iobroker
      tolerations:
      #- effect: NoSchedule
      #  key: node-role.kubernetes.io/master
      containers:
      - name: iobroker
        image: buanet/iobroker:latest-v10
        imagePullPolicy: IfNotPresent

          #command: 
          #- sh 
          #- -c 
          #- while [ 1 ]; do sleep 10;done 
        resources:
          requests:
            memory: "1024Mi"
            cpu: "50m"
        ports:
        - containerPort: 8081  #original admin
        - containerPort: 8082  #original vis
        - containerPort: 8084  #original io sockets
        - containerPort: 8087  #original SimpleAPI
        - containerPort: 1883  #original mqtt
        - containerPort: 8400  #original jarvis
        - containerPort: 30888 #original nodered
        - containerPort: 32001 #hrpc.0
        - containerPort: 8701  #hrpc.1
        - containerPort: 32010 #hrpc.2
        - containerPort: 30292 #hrpc.3
        - containerPort: 30004 #hrpc.4
        - containerPort: 30005 #hrpc.5
        - containerPort: 30081 #Reconfigured admin
        - containerPort: 30082 #Reconfigured vis
        - containerPort: 30087 #Reconfigured SimpleAPI
        - containerPort: 30170 #reconfigired mqt
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 600 # 10 minutes
          timeoutSeconds: 5
          failureThreshold: 3 # 2 minutes
        env:
        - name: TZ
          value: Europe/Berlin
            #        - name: IOB_STATESDB_HOST
            #          value: rdis-master
            #        - name: IOB_STATESDB_PORT
            #          value: "6379"
            #        - name: IOB_STATESDB_TYPE
            #          value: redis
            #        - name: IOB_STATESDB_PASS
            #          value: yPRzQYIlOY
        - name:  PACKAGES
          value: cifs-utils redis-server 
        volumeMounts:
        - mountPath: /opt/iobroker/
          name: pv-iobrokerdata
        - mountPath: /opt/iobroker/backups
          name: pv-backup    
        - mountPath: /opt/scripts/.docker_config/
          name: health
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - DAC_READ-SEARCH 
            - NET_ADMIN
      volumes:
        - name: pv-iobrokerdata
          persistentVolumeClaim:
           claimName: iobrokerdata
        - name: pv-backup
          persistentVolumeClaim:
           claimName: backup
        - name: health
          emptyDir: {}
          #hostPath:
              #path: "/opt/scripts"
              #glusterfs:
              #endpoints: heketi-storage-endpoints
              #path: iobroker
              #- name: scripts
              #emptyDir: {}

---


